# Generated by Django 4.2.1 on 2023-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoapp', '0002_mecanico_agnos_exp_mecanico_educacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_mecanico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_encabezado', models.CharField(max_length=100, null=True, verbose_name='Nombre_Encabezado')),
                ('expertiz_encabezado', models.CharField(max_length=100, null=True, verbose_name='Expertiz_Encabezado')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=100, null=True, verbose_name='Especialidad')),
                ('titulos', models.CharField(max_length=100, null=True, verbose_name='Titulos')),
                ('agnos_exp', models.CharField(max_length=100, null=True, verbose_name='Años_Experiencia')),
                ('resumen_pro', models.CharField(max_length=1000, null=True, verbose_name='Resumen_Pro')),
                ('resumen_edu', models.CharField(max_length=1000, null=True, verbose_name='Resumen_Edu')),
                ('resumen_exp', models.CharField(max_length=1000, null=True, verbose_name='Resumen_Exp')),
                ('trabajo_uno', models.CharField(max_length=100, null=True, verbose_name='Trabajo_Uno')),
                ('desc_tra_uno', models.CharField(max_length=1000, null=True, verbose_name='Descripción_tra_uno')),
                ('trabajo_dos', models.CharField(max_length=100, null=True, verbose_name='Trabajo_Dos')),
                ('desc_tra_dos', models.CharField(max_length=1000, null=True, verbose_name='Descripción_tra_dos')),
                ('trabajo_tres', models.CharField(max_length=100, null=True, verbose_name='Trabajo_Tres')),
                ('desc_tra_tres', models.CharField(max_length=1000, null=True, verbose_name='Descripción_tra_tres')),
            ],
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='agnos_exp',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='educacion',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
