# Generated by Django 4.2.1 on 2023-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoapp', '0003_detalle_mecanico_remove_mecanico_agnos_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_mecanico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='desc_tra_dos',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descripción_tra_dos'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='desc_tra_tres',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descripción_tra_tres'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='desc_tra_uno',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descripción_tra_uno'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='resumen_edu',
            field=models.TextField(max_length=1000, null=True, verbose_name='Resumen_Edu'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='resumen_exp',
            field=models.TextField(max_length=1000, null=True, verbose_name='Resumen_Exp'),
        ),
        migrations.AlterField(
            model_name='detalle_mecanico',
            name='resumen_pro',
            field=models.TextField(max_length=1000, null=True, verbose_name='Resumen_Pro'),
        ),
    ]
